sudo: false
language: node_js

matrix:
  include:
  - node_js: 8
    env: CXX=g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn lint
  - yarn test
  - yarn commitlint
  - yarn coverage -- -u -p codecov coveralls

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
